name: GH Actions CI
permissions: {}
concurrency:
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'hibernate/hibernate-orm' }}
jobs:
  build:
    permissions:
      contents: read
    name: OpenJDK 25 - ${{matrix.rdbms}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - rdbms: h2
        - rdbms: hsqldb
        - rdbms: mysql
        - rdbms: mariadb
        - rdbms: postgresql
        - rdbms: edb
        - rdbms: oracle
        - rdbms: db2
        - rdbms: mssql
        - rdbms: sybase
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Generate cache key
      id: cache-key
      run: |
        CURRENT_BRANCH="${{ github.repository != 'hibernate/hibernate-orm' && 'fork' || github.base_ref || github.ref_name }}"
        CURRENT_MONTH=$(/bin/date -u "+%Y-%m")
        CURRENT_DAY=$(/bin/date -u "+%d")
        ROOT_CACHE_KEY="buildtool-cache"
        echo "buildtool-monthly-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}" >> $GITHUB_OUTPUT
        echo "buildtool-monthly-branch-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}-${CURRENT_BRANCH}" >> $GITHUB_OUTPUT
        echo "buildtool-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}-${CURRENT_BRANCH}-${CURRENT_DAY}" >> $GITHUB_OUTPUT
  otp:
    permissions:
      contents: read
    name: GraalVM 25 - ${{matrix.rdbms}}
    runs-on:
    - self-hosted
    - Linux
    - X64
    - OracleTestPilot
    if: github.repository == 'elcolloff/hibernate-orm'
    strategy:
      fail-fast: false
      matrix:
        include:
        - rdbms: base-database-service-19c
        - rdbms: base-database-service-21c
        - rdbms: base-database-service-26ai
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Set up Java 25
      uses: graalvm/setup-graalvm@f744c72a42b1995d7b0cbc314bde4bace7ac1fe1
      with:
        distribution: graalvm
        java-version: '25'
    - name: Generate cache key
      id: cache-key
      run: |
        CURRENT_BRANCH="${{ github.repository != 'hibernate/hibernate-orm' && 'fork' || github.base_ref || github.ref_name }}"
        CURRENT_MONTH=$(/bin/date -u "+%Y-%m")
        CURRENT_DAY=$(/bin/date -u "+%d")
        ROOT_CACHE_KEY="buildtool-cache-oracle-test-pilot"
        echo "buildtool-monthly-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}" >> $GITHUB_OUTPUT
        echo "buildtool-monthly-branch-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}-${CURRENT_BRANCH}" >> $GITHUB_OUTPUT
        echo "buildtool-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}-${CURRENT_BRANCH}-${CURRENT_DAY}" >> $GITHUB_OUTPUT
    - name: Cache Maven/Gradle Dependency/Dist Caches
      id: cache-maven
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
      if: github.event_name != 'pull_request'
      with:
        path: |
          ~/.m2/repository/
          ~/.m2/wrapper/
          ~/.gradle/caches/
          !~/.gradle/caches/build-cache-*
          ~/.gradle/wrapper/
        key: ${{ steps.cache-key.outputs.buildtool-cache-key }}
        restore-keys: |
          ${{ steps.cache-key.outputs.buildtool-monthly-branch-cache-key }}-
          ${{ steps.cache-key.outputs.buildtool-monthly-cache-key }}-
    - name: Restore Maven/Gradle Dependency/Dist Caches
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
      if: github.event_name == 'pull_request'
      with:
        path: |
          ~/.m2/repository/
          ~/.m2/wrapper/
          ~/.gradle/caches/
          !~/.gradle/caches/build-cache-*
          ~/.gradle/wrapper/
        key: ${{ steps.cache-key.outputs.buildtool-cache-key }}
        restore-keys: |
          ${{ steps.cache-key.outputs.buildtool-monthly-branch-cache-key }}-
          ${{ steps.cache-key.outputs.buildtool-monthly-cache-key }}-
    - id: create_database
      uses: oracle-actions/setup-testpilot@f620f11f9f26dacfe80ba1823342e3e92604c55f
      with:
        oci-service: ${{ matrix.rdbms }}
        action: create
        user: hibernate_orm_test_1,hibernate_orm_test_2,hibernate_orm_test_3,hibernate_orm_test_4,hibernate_orm_test_5,hibernate_orm_test_6,hibernate_orm_test_7,hibernate_orm_test_8
    - name: Run build script
      env:
        RDBMS: ${{ matrix.rdbms }}
        RUNID: ${{ github.run_number }}
        TESTPILOT_CONNECTION_STRING_SUFFIX: ${{ steps.create_database.outputs.connection_string_suffix }}
        TESTPILOT_PASSWORD: ${{ steps.create_database.outputs.database_password }}
        API_HOST: ''
        TESTPILOT_CLIENT_ID: ''
        TESTPILOT_TOKEN: ''
        LD_PRELOAD: /home/ubuntu/libtfojdbc1.so
        LD_LIBRARY_PATH: /home/ubuntu
        GRADLE_OPTS: -Dorg.gradle.workers.max=8
        ORG_GRADLE_JVMARGS: -Dlog4j2.disableJmx -Xmx4g -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Duser.language=en -Duser.country=US -Duser.timezone=UTC -Dfile.encoding=UTF-8
        ORG_GRADLE_PROJECT_toolchain.compiler.jvmargs: -Dlog4j2.disableJmx=true -Xmx4g -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Duser.language=en -Duser.country=US -Duser.timezone=UTC -Dfile.encoding=UTF-8
        ORG_GRADLE_PROJECT_toolchain.launcher.jvmargs: -Dlog4j2.disableJmx=true -Xmx3g -XX:MaxMetaspaceSize=448m -XX:+HeapDumpOnOutOfMemoryError -Duser.language=en -Duser.country=US -Duser.timezone=UTC -Dfile.encoding=UTF-8
      run: ./ci/build-github.sh
      shell: bash
    - uses: oracle-actions/setup-testpilot@f620f11f9f26dacfe80ba1823342e3e92604c55f
      if: always()
      with:
        oci-service: ${{ matrix.rdbms }}
        action: delete
        user: hibernate_orm_test_1,hibernate_orm_test_2,hibernate_orm_test_3,hibernate_orm_test_4,hibernate_orm_test_5,hibernate_orm_test_6,hibernate_orm_test_7,hibernate_orm_test_8
    - name: Upload GitHub Actions artifact for the Develocity build scan
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      if: ${{ !cancelled() }}
      with:
        name: build-scan-data-${{ matrix.rdbms }}
        path: ~/.gradle/build-scan-data
    - name: Store coverage report
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: build-coverage-data-${{ matrix.rdbms }}
        retention-days: 1
        path: |
          ./**/target/jacoco/*.exec
    - name: Upload test reports (if Gradle failed)
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      if: failure()
      with:
        name: test-reports-java11-${{ matrix.rdbms }}
        path: |
          ./**/target/reports/tests/
    - name: Omit produced artifacts from build cache
      run: ./ci/before-cache.sh
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
on:
  push:
    branches:
    - main
    - '!dependabot/**'
  pull_request:
    branches:
    - main
    - '!dependabot/**'
    - dependabot/maven/build-dependencies-**
    - dependabot/github_actions/workflow-actions-**
